config/routes.rb
Rails.application.routes.draw do
  resources :contents do
    member do
      get 'approve'
    end
  end
  # get 'homepage/index'
  root 'homepage#index', as: 'root'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :dashboard, only: [:index]
  resources :users

  get 'errors/403', to: 'errors#error_403'
  get 'errors/404', to: 'errors#error_404'

  mount Rapidfire::Engine => "/rapidfire"
  resources :assignments
  resources :registration, only: [:new, :create]
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    render :layout => false
  end
end

app/views/homepage/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GO-Academy" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Athena" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# Rails flash messages styled for Bootstrap 4.0 %>
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <div class="container">

      <div class="layer"><%= image_tag "go-academy.png" %></div>
      <div class="jumbotron text-left">
        <div class="row">
          <div class="col-lg-6">
            <h2>Our tech apprenticeship now open!</h2>
            <%= link_to "Register", new_registration_path, class: "btn btn-success" %>
          </div>
          <div class="col-lg-6 text-right">
            <h2></h2>
            <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: "btn btn-success" %>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
            <h2 class=" section-title">ABOUT US</h2>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <h3>Who we are</h3>
            <p>GO-ACADEMY is a talent incubator that produces world class tech talents in Indonesia's Tech Industry</p>
          </div>
          <div class="col-sm-4">
            <h3>Our mission</h3>
            <p>By producing more world class tech talents, we can unleash Indonesia's greatest potential</p>
          </div>
          <div class="col-sm-4">
            <h3>Our approach</h3>
            <p>We have various programs curated for you. Find out which one suits you best!</p>
          </div>
        </div>

        <div class="layer">
          <div class="row">
              <h2 class=" section-title">OUR PROGRAMS</h2>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <%= image_tag "go-academy-tech-apprentice.jpg", class: "section-img" %>
            </div>
            <div class="col-sm-6 section-text">
              <h3>TECH APPRENTICESHIP</h3>
              <p>6-month program to transform aspiring software engineers into industry ready ones.</p>
              <p>You will work on complex technology projects and develop skills in writing clean code, Test Driven Development, Design Pattern, CI/CD, Container, Mobile Development, UX Design, and Data Science in a highly diverse working environment.</p>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 section-text">
              <h3>TECH AND BUSINESS INTELLIGENCE INTERNSHIP</h3>
              <p>12-week tech internship program for students with tech backgrounds</p>
              <p>We started with a 1-week boot camp about industry best practices followed by 11-weeks of working on exciting, impactful, and complex tech projects using Elasticsearch, Kubernetes, Docker, LXD, Golang, Ruby, Kafka, etc. while being closely mentored by our senior leaders. Check out our timeline here!</p>
            </div>
            <div class="col-sm-6">
              <%= image_tag "go-academy-tech-bi.jpg", class: "section-img" %>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <%= image_tag "go-academy-tech-campus-engagement.jpg", class: "section-img" %>
            </div>
            <div class="col-sm-6 section-text">
              <h3>TECH CAMPUS ENGAGEMENT</h3>
              <p>Customized hands-on workshops in partnership with universities to get tech students up to date with current industry practices.</p>
              <p>In our previous programs, we've drilled down on Test Driven Development, Design Pattern, Microservices, CI/CD, DevOps, Agile, and many other things!</p>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 section-text">
              <h3>TECH BLOG</h3>
              <p>Stories from our engineers about GO-JEK's work, culture & practices</p>
              <p>Find out more how we manage 1 million drivers with 12 engineers, build resilience in large scale distributed systems, and handle microservices at scale!</p>
            </div>
            <div class="col-sm-6">
              <%= image_tag "go-academy-tech-blog.png", class: "section-img" %>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <%= image_tag "go-academy-tech-talk.jpg", class: "section-img" %>
            </div>
            <div class="col-sm-6 section-text">
              <h3>TECH TALK</h3>
              <p>Insightful talks by Go-Jek engineers in collaboration with tech communities and companies to share relevant practices</p>
              <p>We name our talks, GO-TALK. Previously we collaborated with JVM User Group, ID Ruby, GoJakarta, Jakarta JS, UXID, Google, Amazon, and many more. Find out more about our next GO-TALK!</p>
            </div>
          </div>
        </div>

        <div class="row">
          <h2 class="section-title">OUR PARTNERS</h2>
        </div>
        <div class="layer">
          <ul class="inline">
            <li><%= image_tag "partners/hacktiv8.jpeg", class: "list-img" %></li>
            <li><%= image_tag "partners/dicoding.png", class: "list-img" %></li>
            <li><%= image_tag "partners/Kolla-Space.png", class: "list-img" %></li>
            <li><%= image_tag "partners/compfest.jpg", class: "list-img" %></li>
          </ul>
        </div>

        <div class="row">
          <ul class="inline">
            <li class="active"><a href="/">About us</a></li>
            <li><a href="/">Blog</a></li>
            <li><a href="/">FAQ</a></li>
            <li><a href="/careers/">Careers</a></li>
            <li><a href="/faq/">Contact Us</a></li>
            <li><a href="/contact/">Media Gallery</a></li>
          </ul>
        </div>
      </div>

    </div>
  </body>
</html>