config/routes.rb
Rails.application.routes.draw do
  resources :contents do
    member do
      get 'approve'
    end
  end
  # get 'homepage/index'
  root 'homepage#index', as: 'root'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :dashboard, only: [:index]
  resources :users

  get 'errors/403', to: 'errors#error_403'
  get 'errors/404', to: 'errors#error_404'

  mount Rapidfire::Engine => "/rapidfire"
  resources :assignments
  resources :registration, only: [:new, :create]
end

app/models/content.rb
class Content < ApplicationRecord
  default_scope { order(created_at: :desc) }
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :type, :module, :level, :access
  mount_uploader :video, VideoUploader
  mount_uploader :attachment, FileUploader

  validates_processing_of :video
  before_save :append_tag_list

  private
  def append_tag_list
    tag_list << module_list unless tag_list.include? module_list
    tag_list << level_list unless tag_list.include? level_list
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :check_session
  before_action :authorize, except: [:index, :show]
  before_action :set_content, only: [:show, :edit, :update, :destroy, :approve]

  def index
    @contents = scoped_contents.where(enabled: true)
    @contents_in_review = Content.tagged_with('material', on: :type)
      .where(enabled: false)

    if params[:term]
      @contents = @contents
        .where("title LIKE :term OR description LIKE :term", term: "%#{params[:term]}%")
      @contents_in_review = @contents_in_review
        .where("title LIKE :term OR description LIKE :term", term: "%#{params[:term]}%")
    elsif params[:tag_query]
      @contents = @contents
        .tagged_with(params[:tag_query], on: :tags, any: true)
      @contents_in_review = @contents_in_review
        .tagged_with(params[:tag_query], on: :tags, any: true)
    end

    @contents = @contents
      .page(params[:page]).per(10)
    @contents_in_review = @contents_in_review
      .page(params[:page]).per(10)
  end

  def show
    begin
      @contents = scoped_contents.tagged_with(@content.tag_list, on: :tags, any: true).where.not(id: @content.id).limit(10)
    rescue ActiveRecord::RecordNotFound => e
      redirect_to errors_404_path
    end
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = Content.new(content_params)
    @content.created_by = current_user.id
    @content.enabled = current_user.role.name == 'admin'

    if @content.save
      redirect('Content was successfully created.')
    else
      render :new
    end
  end

  def update
    @content.updated_by = current_user.id

    if @content.update(content_params)
      redirect('Content was successfully updated.')
    else
      render :edit
    end
  end

  def approve
    if current_user.is_admin?
      @content.update(enabled: true)
      redirect_to contents_path
    else
      redirect_to errors_403_path
    end
  end

  def authorize
    authorized_to_modify
  end

  def scoped_contents
    if current_user.is_public_participant?
      Content.tagged_with('material', on: :type).tagged_with('public', on: :access).where(enabled: true)
    elsif current_user.is_authorized_to_modify?
      Content.tagged_with('material', on: :type).all
    else
      Content.tagged_with('material', on: :type).where(enabled: true)
    end
  end

  def redirect(notice)
    redirect_to @content, notice: notice
  end

  private
    def set_content
      begin
        @content = scoped_contents.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to errors_404_path
      end
    end

    def content_params
      params.require(:content).permit(:title, :description, :content, :url,
        :type_list, :module_list, :level_list, :tag_list, :access_list,
        :video, :attachment)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
  MODULES = {
    'Core Engineering' => 'Core Engineering',
    'DevOps' => 'DevOps'
  }

  ACCESSES = {
    'public' => 'public',
    'internal' => 'internal'
  }

  BATCHES = (1..5).inject({}) do |batches, i|
    batches["Batch #{i}"] = i
    batches
  end
end

app/views/contents/_contents.html.erb
    <table>
      <tr>
        <th width="5%">No</th>
        <th width="20%">Title</th>
        <th width="35%">Description</th>
        <th width="15%">Categories</th>
        <th width="15%">Owner</th>
        <th></th>
        <th></th>
      </tr>
      <% contents.each_with_index do |content, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= link_to content.title, content_path(content) %></td>
          <td><%= content.description %></td>
          <td>
            <% content.tag_list.each_with_index do |tag, i| %>
              <%= link_to tag, contents_path(tag_query: tag) %>
              <%= ',' if i < content.tag_list.size - 1 %>
            <% end %>
          </td>
          <td><%= User.get_name(content.created_by) %></td>
          <td><% if current_user.is_authorized_to_modify? %>
            <%= content.enabled ? 'approved' : 'need review' %>
          <% end %></td>
          <td><% if current_user.is_authorized_to_modify? %>
            <a href="<%= edit_content_path(content) %>"><span class="fa fa-pencil"></span></a>
          <% end %></td>
        </tr>
      <% end %>
    </table>

    <br>

    <div class="row">
      <div class="col-sm-4">
        <% if current_user.is_authorized_to_modify? %>
          <%= link_to 'New Content', new_content_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="col-sm-4 text-center">
        <%= paginate @contents %>
      </div>
      <div class="col-sm-4 text-right">
        <%= page_entries_info @contents %>
      </div>
    </div>

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <label class="control-label col-sm-2" for="title">Title</label>
    <div class="col-sm-10">
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="description">Description</label>
    <div class="col-sm-10">
      <%= form.text_field :description, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="content">Content</label>
    <div class="col-sm-10">
      <%= form.text_area :content, class: 'form-control tinymce', rows: 5, cols: 25 %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="url">URL</label>
    <div class="col-sm-10">
      <%= form.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="module_list">Module</label>
    <div class="col-sm-10">
      <%= form.select :module_list, ::ContentsHelper::MODULES, {:prompt=>true}, {id: "module_list", :class=>'form-control'} %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="access_list">Access</label>
    <div class="col-sm-10">
      <%= form.select :access_list, ::ContentsHelper::ACCESSES, {:prompt=>true}, :class=>'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="tag_list">Tag</label>
    <div class="col-sm-10">
      <%= form.text_field :tag_list, value: @content.tag_list.to_s, class: 'form-control' %>
      separate the categories with comma (,)
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="video">Video</label>
    <div class="col-sm-6">
      <%= form.file_field :video, id: 'content-video', class: 'form-control' %>
      <br>
      <small>Only MP4, Ogg, and WebM videos are allowed.</small>
    </div>
    <div class="col-sm-4">
      <% if form.object.video? %>

        <%= form.label :remove_video %>
        <%= form.check_box :remove_video %>
      <% end %>
    </div>
  </div>

  <%= form.hidden_field :type_list, value: 'material' %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
      <%= link_to 'Back', contents_path, class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/contents/_maintainer_contents.html.erb
  <ul class="nav nav-pills" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="pill" href="#approved">Approved</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="pill" href="#review">Need Review</a>
    </li>
  </ul>
<hr>
<div class="tab-content">
  <div id="approved" class="tab-pane active"><br>
    <div class="row">
      <div class="col-md-6"><h2>Contents</h2></div>
      <div class="col-md-6 text-right"><%= render 'search' %></div>
    </div>
    <%= render 'contents', contents: @contents %>
  </div>
  <div id="review" class="tab-pane"><br>
    <h2>Contents in Review</h2>
    <p></p>
    <%= render 'contents', contents: @contents_in_review %>
  </div>
</div>

app/views/contents/_participant_contents.html.erb
<div class="row">
      <div class="col-md-6"><h2>Contents</h2></div>
      <div class="col-md-6 text-right"><%= render 'search' %></div>
    </div>
<p></p>
<%= render 'contents', contents: @contents %>

app/views/contents/_search.html.erb
<%= form_tag(contents_path, method: :get) do %>

  <div class="row">
    <div class="col-sm-10">
      <%= text_field_tag :term, nil, class: 'form-control' %>
    </div>
    <%= submit_tag 'Search', class: 'col-sm-2 btn btn-default' %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="card">
<h2>Edit Content</h2>
<hr>

<%= render 'form', content: @content %>

</div>

app/views/contents/index.html.erb
<% if current_user.is_authorized_to_modify? %>
  <%= render 'maintainer_contents' %>
<% else %>
  <%= render 'participant_contents' %>
<% end %>

app/views/contents/new.html.erb
<div class="card">
<h2>New Content</h2>
<hr>

<%= render 'form', content: @content %>

</div>

app/views/contents/show.html.erb
  <div class="row">
    <div class="col-md-10">
      <div class="content-card">
        <div class="row">
          <div class="col-sm-6">
            <% if current_user.is_authorized_to_modify? %><%= link_to 'Edit', edit_content_path(@content) %> | <% end %>
            <%= link_to 'Back', contents_path %>
          </div>
          <% if !@content.enabled && current_user.is_admin? %>
            <div class="col-sm-6 text-right">
              <%= link_to "Approve This Content",
                approve_content_path(@content),
                data: { confirm: "Are you sure you want to approve this content?" },
                class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>

        <h1><%= @content.title %></h1>
        <h3><%= @content.description %></h3>
        <hr>
        <% unless @content.video.file.nil? %>
          <%= video_tag @content.video, controls: true, autobuffer: true, height: 640 %>
        <hr>
        <% end %>
        <div class='content-content'><%= @content.content.html_safe if @content.content %></div>

        <div class="row">
          <div class="col-sm-6">
            <% if current_user.is_authorized_to_modify? %><%= link_to 'Edit', edit_content_path(@content) %> | <% end %>
            <%= link_to 'Back', contents_path %>
          </div>
          <% if !@content.enabled && current_user.is_admin? %>
            <div class="col-sm-6 text-right">
              <%= link_to "Approve This Content",
                approve_content_path(@content),
                data: { confirm: "Are you sure you want to approve this content?" },
                class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <ul class="right-sidenav">
        <h4 class="right-sidenav-title">Related Materials</h4>
        <% @contents.each_with_index do |content, i| %>
          <li><%= link_to content.title, content_path(content) %></li>
      <% end %>
      </ul>
    </div>
  </div>