config/routes.rb
Rails.application.routes.draw do
  resources :contents do
    member do
      get 'approve'
    end
  end
  # get 'homepage/index'
  root 'homepage#index', as: 'root'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :dashboard, only: [:index]
  resources :users

  get 'errors/403', to: 'errors#error_403'
  get 'errors/404', to: 'errors#error_404'

  mount Rapidfire::Engine => "/rapidfire"
  resources :assignments
  resources :registration, only: [:new, :create]
end

app/controllers/assignments_controller.rb
class AssignmentsController < ContentsController
  def index
    @contents = scoped_contents

    if params[:term]
      @contents = @contents
        .where("title LIKE :term OR description LIKE :term", term: "%#{params[:term]}%")
    elsif params[:tag_query]
      @contents = @contents
        .tagged_with(params[:tag_query], on: :tags, any: true)
    end

    @contents = @contents
      .page(params[:page]).per(10)
  end

  def authorize
    check_if_participant
  end

  def scoped_contents
    contents = Content.tagged_with('assignment', on: :type).all
    if current_user.is_public_participant?
      contents = contents.where(created_by: current_user.id)
    elsif current_user.is_participant?
      contents = contents.joins('LEFT JOIN users ON users.id = contents.created_by').where('users.batch = ?', current_user.batch)
    end
    contents
  end

  def redirect(notice)
    redirect_to assignments_path, notice: 'Assignment submitted'
  end
end

app/views/assignments/_form.html.erb
<%= form_for content, :url => redirect_url do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <label class="control-label col-sm-2" for="title">Title</label>
    <div class="col-sm-10">
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="description">Note</label>
    <div class="col-sm-10">
      <%= form.text_field :description, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="url">URL</label>
    <div class="col-sm-10">
      <%= form.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="module_list">Module</label>
    <div class="col-sm-10">
      <%= form.select :module_list, ::ContentsHelper::MODULES, {}, {id: "module_list", :class=>'form-control'} %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="attachment">Upload File</label>
    <div class="col-sm-6">
      <%= form.file_field :attachment, id: 'content-attachment', class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <% if form.object.attachment? %>

        <%= form.label :remove_attachment %>
        <%= form.check_box :remove_attachment %>
      <% end %>
    </div>
  </div>

  <%= form.hidden_field :type_list, value: 'assignment' %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
      <%= link_to 'Back', assignments_path, class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/assignments/_search.html.erb
<%= form_tag(contents_path, method: :get) do %>

  <div class="row">
    <div class="col-sm-10">
      <%= text_field_tag :term, nil, class: 'form-control' %>
    </div>
    <%= submit_tag 'Search', class: 'col-sm-2 btn btn-default' %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<div class="card">
<h2>Edit Assignment</h2>
<hr>

<%= render 'form', content: @content, redirect_url: assignment_path(@content) %>

</div>

app/views/assignments/index.html.erb
<div class="row">
      <div class="col-md-6"><h2>Assignments</h2></div>
      <div class="col-md-6 text-right"><%= render 'search' %></div>
    </div>
<p></p>

    <table>
      <tr>
        <th width="5%">No</th>
        <th width="15%">Title</th>
        <th width="20%">Note</th>
        <th width="30%">Link</th>
        <th></th>
        <th width="10%">Categories</th>
        <th width="10%">Owner</th>
        <th></th>
        <th width="5%">Batch</th>
        <th></th>
      </tr>
      <% @contents.each_with_index do |content, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= content.title %></td>
          <td><%= content.description %></td>
          <td><%= link_to content.url, content.url %></td>
          <td>
            <% if content.attachment.file.nil? %>
              <a href="<%= content.attachment %>"><span class="fa fa-download"></span></a>
            <% end %>
          </td>
          <td>
            <% content.tag_list.each_with_index do |tag, i| %>
              <%= link_to tag, assignments_path(tag_query: tag) %>
              <%= ',' if i < content.tag_list.size - 1 %>
            <% end %>
          </td>
          <td><%= User.get_name(content.created_by) %></td>
          <td>
            <% if current_user.is_participant? %>
              <a href="<%= edit_assignment_path(content) %>"><span class="fa fa-pencil"></span></a>
            <% end %>
          </td>
          <td>
            <%= "Batch #{User.find(content.created_by).batch || '-'}" %>
          </td>
        </tr>
      <% end %>
    </table>

    <br>

    <div class="row">
      <div class="col-sm-4">
        <% if current_user.is_participant? || current_user.is_public_participant? %>
          <%= link_to 'Submit New Assignment', new_assignment_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="col-sm-4 text-center">
        <%= paginate @contents %>
      </div>
      <div class="col-sm-4 text-right">
        <%= page_entries_info @contents %>
      </div>
    </div>

app/views/assignments/new.html.erb
<div class="card">
<h2>Submit Assignment</h2>
<hr>

<%= render 'form', content: @content, redirect_url: assignments_path %>

</div>