config/routes.rb
Rails.application.routes.draw do
  resources :contents do
    member do
      get 'approve'
    end
  end
  # get 'homepage/index'
  root 'homepage#index', as: 'root'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :dashboard, only: [:index]
  resources :users

  get 'errors/403', to: 'errors#error_403'
  get 'errors/404', to: 'errors#error_404'

  mount Rapidfire::Engine => "/rapidfire"
  resources :assignments
  resources :registration, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  default_scope { order(created_at: :desc) }
  mount_uploader :photo, ImageUploader

  FORMAT_URL = /\A(https?):\/\/([\w\d]+([\-\.]{1}[\w\d]+)*(\.\w{2,})|(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))(:\d{1,5})?((\/|\?).*)?\z/ix
  GMAIL_DOMAINS = %w{gmail.com googlemail.com}

  belongs_to :role
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true
  validates :email, uniqueness: true, if: :never_signed_in
  validates :phone, presence: true, unless: :uid
  validates :phone, uniqueness: true, allow_blank: true
  validates :git_url, :linkedin_url, format: { with: FORMAT_URL }, allow_blank: true
  validate :confirm_gmail, if: :never_signed_in
  validates :photo, file_size: { less_than: 0.5.megabyte }
  validates_processing_of :photo


  def self.from_omniauth(auth)
    where("email = ? OR (provider = ? AND uid = ?)", auth.info.email, auth.provider, auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email
      user.image = auth.info.image
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.get_name(id)
    User.find(id).name
  end

  def is_authorized_to_modify?
    is_admin? || role.name == 'mentor'
  end

  def is_admin?
    role.name == 'admin'
  end

  def is_participant?
    role.name == 'participant'
  end

  def is_public_participant?
    role.name == 'public_participant'
  end

  private
  def confirm_gmail
    unless email_is_gmail
      errors[:email] << 'can only be Gmail for better integration'
    end
  end

  def email_is_gmail
    GMAIL_DOMAINS.each do |domain|
      return true if email.end_with?('@' + domain)
    end
    return false
  end

  def never_signed_in
    User.find_by(email: email).nil?
  end

  def photo_size_validation
    errors[:photo] << "should be less than 500KB" if photo.size > 0.5.megabytes
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_session, :check_if_admin, except: :show
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.page(params[:page])
  end

  def new
    @user = User.new
  end

  def show
    unless current_user.is_admin? or current_user.id == @user.id
      redirect_to errors_403_path
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :role_id, :email, :phone, :git_url, :image, :linkedin_url, :photo, :batch)
    end
end

app/views/users/edit.html.erb
<div class="card">
<h2>Edit User</h2>
<hr>
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <label class="control-label col-sm-2" for="email">Email</label>
    <div class="col-sm-10">
      <%= form.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <label class="control-label col-sm-2" for="phone">Phone</label>
    <div class="col-sm-4">
      <%= form.text_field :phone, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="email">Name</label>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="email">Role</label>
    <div class="col-sm-10">
      <%= form.collection_select(:role_id, Role.all, :id, :name, {:prompt=>true}, {:class=>'form-control'}) %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="batch">Batch</label>
    <div class="col-sm-10">
      <%= form.select :batch, ::ContentsHelper::BATCHES, {:prompt=>true}, :class=>'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
      <%= link_to 'Back', users_path, class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>
</div>

app/views/users/index.html.erb
<h2>Users</h2>
<p></p>
<table>
  <tr>
    <th></th>
    <th></th>
    <th>Name</th>
    <th>Email</th>
    <th>Batch</th>
    <th>Role</th>
    <th></th>
  </tr>
  <% @users.each_with_index do |user, i| %>
    <tr>
      <td><%= i + 1 %></td>
      <td width="10%">
        <% if !user.photo.file.nil? %>
          <%= image_tag user.photo.thumb.url %>
        <% elsif user.image %>
          <%= image_tag user.image, class: 'logo' %>
        <% else %>
          <h1><span class="fa fa-user"></span></h1>
        <% end %>
      </td>
      <% user_name = user.name unless user.name.nil? %>
      <td><%= link_to user_name, user_path(user) %></td>
      <td><%= link_to user.email, user_path(user) %></td>
      <td><%= user.batch %></td>
      <td><%= user.role.name unless user.role.nil? %></td>
      <td><a href="<%= edit_user_path(user) %>"><span class="fa fa-pencil"></span></a></td>
    </tr>
  <% end %>
</table>
<br>

<div class="row">
  <div class="col-sm-4">
    <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-sm-4 text-center">
    <%= paginate @users %>
  </div>
  <div class="col-sm-4 text-right">
    <%= page_entries_info @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="card">
<h2>New User</h2>
<hr>
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <label class="control-label col-sm-2" for="email">Email</label>
    <div class="col-sm-10">
      <%= form.text_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="email">Name</label>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="email">Role</label>
    <div class="col-sm-10">
      <%= form.collection_select(:role_id, Role.all, :id, :name, {:prompt=>true}, {:class=>'form-control'}) %>
    </div>
  </div>

  <div class="row">
    <label class="control-label col-sm-2" for="batch">Batch</label>
    <div class="col-sm-10">
      <%= form.select :batch, ::ContentsHelper::BATCHES, {:prompt=>true}, :class=>'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
      <%= link_to 'Back', users_path, class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>
</div>

app/views/users/show.html.erb
<div class="card">
  <h1>User Info</h1>
  <hr>
  <div class="row">
    <div class="col-sm-6">
      <% if !@user.photo.file.nil? %>
          <%= image_tag @user.photo.url, width: 420 %>
        <% elsif @user.image %>
          <%= image_tag @user.image, width: 420, height: 420 %>
        <% else %>
          <h1><span class="fa fa-user"></span></h1>
        <% end %>
    </div>
    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-3"><h4>Name</h4></div>
        <div class="col-sm-9"><%= @user.name %></div>
      </div>
      <div class="row">
        <div class="col-sm-3"><h4>Email</h4></div>
        <div class="col-sm-9"><%= @user.email %></div>
      </div>
      <div class="row">
        <div class="col-sm-3"><h4>Phone</h4></div>
        <div class="col-sm-9"><%= @user.phone %></div>
      </div>

      <div class="row">
        <div class="col-sm-3"><h4>Role</h4></div>
        <div class="col-sm-9"><%= @user.role.name %></div>
      </div>
      <div class="row">
        <div class="col-sm-3"><h4>Batch</h4></div>
        <div class="col-sm-9"><%= @user.batch %></div>
      </div>
      <div class="row">
        <div class="col-sm-3"><h4>GIT link</h4></div>
        <div class="col-sm-9">
          <% if @user.linkedin_url %>
            <%= link_to @user.git_url, @user.git_url %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3"><h4>LinkedIn link</h4></div>
        <div class="col-sm-9">
          <% if @user.linkedin_url %>
            <%= link_to @user.linkedin_url, @user.linkedin_url %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <% if current_user.is_admin? %>
        <%= link_to 'Back', users_path, class: 'btn btn-primary' %>
      <% else %>
        <%= link_to 'Back', dashboard_index_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>